version: "3.8"

services:
  web: &web
    build:
      context: .
      dockerfile: ./compose/backend/Dockerfile
    restart: unless-stopped
    command: uvicorn server.asgi:application --host 0.0.0.0 --reload
    depends_on:
      - db
      - redis
    volumes:
      - ./backend:/home/server:z
      - static_volume:/home/server/static
      - media_volume:/home/server/media
    ports:
      - "8000:8000"
    env_file:
      - .envs/development/web.env
      - .envs/development/db.env
      - .envs/development/rabbitmq.env
    networks:
      - project-network

  worker:
    <<: *web
    command: celery -A server worker -B -l info --loglevel=info
    depends_on:
      - rabbit-mq
      - db
    ports: [ ]
    networks:
      - project-network

  db:
    image: postgres:12.2
    ports:
      - "5432:5432"
    env_file:
      - .envs/development/db.env
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    networks:
      - project-network

  redis:
    image: redis:6.2.6-alpine
    networks:
      - project-network

  rabbit-mq:
    image: rabbitmq:3.9.11-management
    env_file:
      - .envs/development/rabbitmq.env
    networks:
      - project-network

networks:
  project-network:
    name: bc-network

volumes:
  postgres_volume: { }
  static_volume: { }
  media_volume: { }
