# Generated by Django 4.0.3 on 2022-04-11 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transformerurl',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='transformerurl',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, verbose_name='Url generada'),
        ),
        migrations.AlterField(
            model_name='transformerurl',
            name='url',
            field=models.CharField(max_length=255, verbose_name='Url destino'),
        ),
        migrations.AlterField(
            model_name='transformerurl',
            name='visited_count',
            field=models.IntegerField(default=0, verbose_name='Cantidad de visitads'),
        ),
    ]
