# Generated by Django 4.0.3 on 2023-03-30 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortenedurl',
            name='slug',
            field=models.CharField(max_length=100, unique=True, verbose_name='Original URL'),
        ),
    ]
