# Generated by Django 4.0.3 on 2022-04-11 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_transformerurl_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transformerurl',
            options={'verbose_name': 'Url generada', 'verbose_name_plural': 'Urls generadas'},
        ),
    ]
