# Generated by Django 4.0.3 on 2022-04-11 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_transformerurl_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='transformerurl',
            name='title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Título'),
        ),
    ]
